### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by GriffinMartin** [GriffinMartin/MI-449-SS17-740-css-stealing-styles-xedvDK#1]
@egillespie Can you take a look at this? It's [hosted here](https://GriffinMartin.github.io/MI-449-SS17-740-css-stealing-styles-xedvDK/) and meets the following criteria:

- [x] The page includes the name of your search engine in big letters (you can make it up), with a search `input` below it, then a button below that to run the search (the button doesn't have to do anything for this prototype)
- [x] The font size of the search engine name is at least 70 pixels, so that it's very easy to see
- [x] `span` elements are wrapped around each letter of the name, like this: `<span>G</span><span>o</span><span>o</span><span>g</span><span>l</span><span>e</span>`, so that they can be styled individually with classes
- [x] The on-hover colors from the paragraphs [on this page](http://skillful-clouds.surge.sh/) are used to color individual letters of your name (similar to the letters in Google's logo)
- [x] Inspect the `input` element at the bottom of the [_Prototyping states_ page of the lesson](5) to create an identical-looking search box for your own site (it should even use the same styles on `focus`)
- [x] The styles from the "Create Account" button [on this page](http://plant-servant.surge.sh/) are used for your "Search" button (it should even use the same styles on `hover` and `active`)
- [x] There are no stylelint errors in your CSS (this will also be expected for all future projects)
- [x] All your CSS exists in a `.css` file

**Comment by egillespie** [comment]
Hey @GriffinMartin, this is an excellent start! 🎩  There are only a couple of subtle differences between the source styles and your own that I can see:

### Font size of search box

The font size of your text box is quite a bit smaller than the one used in the [prototype](https://msu.lansing.codes/courses/MI-449-SS17-740/lessons/css-stealing-styles/5). Can you increase the font size to match?

### Border and outline on the search button

There's a gray border on your search button that does not exist on the [prototype](http://plant-servant.surge.sh/). Can you remove the border?

When I click the button, a blue outline appears around the button as well. Can you remove that too?

---

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! :rocket:

**Comment by GriffinMartin** [comment]
@egillespie Fixed it up! Thanks 🎉

**Comment by egillespie** [comment]
Fantastico! Great work! :shipit:
